apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtor-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produtor-api
  template:
    metadata:
      labels:
        app: produtor-api
    spec:
      containers:
      - name: produtor-api
        image: fiaptechchallenge.azurecr.io/contatos.produtor.inclusao.api
        envFrom:
          - configMapRef:
             name: configmap-api
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: produtor-api
spec:
  type: LoadBalancer
  ports:
  - port: 5075
    targetPort: 8080
  selector:
    app: produtor-api
